using WordWise.Api.Models.Domain;
using WordWise.Api.Models.Dto.WritingExercise;

namespace WordWise.Api.Services.Interface
{
    public interface IWritingExerciseService
    {
        Task<string> GetFeedBackFromAi(Guid writingExerciseId);
        Task<ResponseAutoGenerateDto> AutoGenerateByAi(WritingExercise writingExercise);
    }
}
