namespace WordWise.Api.Models.Dto.WritingExercise
{
    public class ResponseAutoGenerateDto
    {
        public Guid WritingExerciseId { get; set; }
        public string Topic { get; set; }

    }
}
